apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awspca-issuer-plugin 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager 
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://cert-manager.github.io/aws-privateca-issuer'
    targetRevision: v1.2.5 
    chart: aws-privateca-issuer
    helm:
      values: |
        image:
          tag: v1.2.5
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
